you can find the source here<br>
<a href="https://github.com/pooya-mohammadi/intro_to_python/blob/master/intro_to_python%5Bfa%5D/Session_04/exercises.ipynb">github</a>

1.Write a NumPy program to create a 5x5 array with random values and find the minimum and maximum values.

In [1]:
import numpy as np

In [2]:
a = np.random.rand(5,5)
print(f"in a :{a} \n max is {np.max(a)}, min ia,{a.min()}")


in a :[[0.29315801 0.8106635  0.96867428 0.15684078 0.87719628]
 [0.6542717  0.87722312 0.96942527 0.57731968 0.73348076]
 [0.13010249 0.25730543 0.80003625 0.04074244 0.18870923]
 [0.33902369 0.5917742  0.28146896 0.26939352 0.03339868]
 [0.9943818  0.20768607 0.01245186 0.20848802 0.20402963]] 
 max is 0.9943818004911369, min ia,0.012451861271654097


Write a NumPy program to create a random 10x4 array and extract the first five rows of the array and store them into a variable.

In [3]:
z = np.random.randint(0, 100, (10,4))
c = z[:5,:]
print(f"{c} is first five row of{z}")

[[ 6 24 25 67]
 [99  3 63  2]
 [52 91 37 12]
 [ 8  9  5 16]
 [89 72 61 82]] is first five row of[[ 6 24 25 67]
 [99  3 63  2]
 [52 91 37 12]
 [ 8  9  5 16]
 [89 72 61 82]
 [84  8 10 45]
 [98 32 86 87]
 [61 27 63 75]
 [13  1 91 45]
 [ 8 74  7 23]]


Write a NumPy program to create random vector of size 15 and replace the maximum value by -1

In [4]:
z = np.random.random_sample((2, 3))
zmax_ = np.where(z == np.max(z), -1, z)

z,zmax_

(array([[0.48876851, 0.91902738, 0.40872277],
        [0.39654857, 0.3748667 , 0.06891309]]),
 array([[ 0.48876851, -1.        ,  0.40872277],
        [ 0.39654857,  0.3748667 ,  0.06891309]]))

normalize an array so the values range exactly between 0 and 1?

In [5]:
z = np.random.randint(100, 200, (3,4))
normalized_z = (z-z.min()) / (z.max()-z.min())
z,normalized_z

(array([[100, 122, 100, 104],
        [160, 152, 120, 192],
        [178, 143, 123, 104]]),
 array([[0.        , 0.23913043, 0.        , 0.04347826],
        [0.65217391, 0.56521739, 0.2173913 , 1.        ],
        [0.84782609, 0.4673913 , 0.25      , 0.04347826]]))

In [6]:

normalize_n_z=(((z-z.mean())/z.std()) + 3) / 6
normalize_n_z

array([[0.31697092, 0.43837714, 0.31697092, 0.33904478],
       [0.6480788 , 0.60393108, 0.42734022, 0.82466967],
       [0.74741116, 0.5542649 , 0.44389561, 0.33904478]])

convert an array of arrays into a flat 1d array

In [9]:
arr=np.random.random((2,3))
r=arr.reshape(-1,)
r,r.shape,r.ndim

(array([0.71537673, 0.87314509, 0.37862333, 0.97418981, 0.60435176,
        0.95795519]),
 (6,),
 1)

#### from 2010 to 2018 group weekdays and weekends in two lists

##### notes: you are allowed to just use datetime or numpy datetime


In [65]:
# make whole date array
weeks = np.arange("2010-01-01","2018-01-01", dtype='datetime64')

# make weekend set
# why set? it's easy way to subtraction 
weekends = set(np.hstack((weeks[1::7], weeks[2::7])))
weeks = set(weeks)
weekday = weeks - weekends

# make them to list
weekday = list(weekday)
weekends = list(weekends)


#### another way

In [57]:
# make whole list
weeks = np.arange("2010-01-01","2018-01-01", dtype='datetime64')
weeks[:8]

array(['2010-01-01', '2010-01-02', '2010-01-03', '2010-01-04',
       '2010-01-05', '2010-01-06', '2010-01-07', '2010-01-08'],
      dtype='datetime64[D]')

In [39]:
# separate weekends_2010,1,1 is friday
weekends = np.hstack((weeks[1::7],weeks[2::7]))
np.sort(weekends)


array(['2010-01-02', '2010-01-03', '2010-01-09', '2010-01-10',
       '2010-01-16', '2010-01-17', '2010-01-23', '2010-01-24',
       '2010-01-30', '2010-01-31', '2010-02-06', '2010-02-07',
       '2010-02-13', '2010-02-14', '2010-02-20', '2010-02-21',
       '2010-02-27', '2010-02-28', '2010-03-06', '2010-03-07',
       '2010-03-13', '2010-03-14', '2010-03-20', '2010-03-21',
       '2010-03-27', '2010-03-28', '2010-04-03', '2010-04-04',
       '2010-04-10', '2010-04-11', '2010-04-17', '2010-04-18',
       '2010-04-24', '2010-04-25', '2010-05-01', '2010-05-02',
       '2010-05-08', '2010-05-09', '2010-05-15', '2010-05-16',
       '2010-05-22', '2010-05-23', '2010-05-29', '2010-05-30',
       '2010-06-05', '2010-06-06', '2010-06-12', '2010-06-13',
       '2010-06-19', '2010-06-20', '2010-06-26', '2010-06-27',
       '2010-07-03', '2010-07-04', '2010-07-10', '2010-07-11',
       '2010-07-17', '2010-07-18', '2010-07-24', '2010-07-25',
       '2010-07-31', '2010-08-01', '2010-08-07', '2010-

In [44]:
a = [weeks[i::7] for i in range(3,7)]
a = np.array(a)
a = a.reshape(1668)


In [45]:
b = weeks[0::7]
b.ndim
b

array(['2010-01-01', '2010-01-08', '2010-01-15', '2010-01-22',
       '2010-01-29', '2010-02-05', '2010-02-12', '2010-02-19',
       '2010-02-26', '2010-03-05', '2010-03-12', '2010-03-19',
       '2010-03-26', '2010-04-02', '2010-04-09', '2010-04-16',
       '2010-04-23', '2010-04-30', '2010-05-07', '2010-05-14',
       '2010-05-21', '2010-05-28', '2010-06-04', '2010-06-11',
       '2010-06-18', '2010-06-25', '2010-07-02', '2010-07-09',
       '2010-07-16', '2010-07-23', '2010-07-30', '2010-08-06',
       '2010-08-13', '2010-08-20', '2010-08-27', '2010-09-03',
       '2010-09-10', '2010-09-17', '2010-09-24', '2010-10-01',
       '2010-10-08', '2010-10-15', '2010-10-22', '2010-10-29',
       '2010-11-05', '2010-11-12', '2010-11-19', '2010-11-26',
       '2010-12-03', '2010-12-10', '2010-12-17', '2010-12-24',
       '2010-12-31', '2011-01-07', '2011-01-14', '2011-01-21',
       '2011-01-28', '2011-02-04', '2011-02-11', '2011-02-18',
       '2011-02-25', '2011-03-04', '2011-03-11', '2011-

In [46]:
# separate weekdays
weekdays = np.hstack((a,b))
print(np.sort(weekdays))

['2010-01-01' '2010-01-04' '2010-01-05' ... '2017-12-27' '2017-12-28'
 '2017-12-29']


<h1 style="background-color:#808000;"></h1>

another source:<br>
<a hrf="https://www.practiceprobs.com/problemsets/python-numpy/beginner">site</a>

With your high school reunion fast approaching, you decide to get in shape and lose some weight
. You record your weight every day for five weeks starting on a Monday.<br>
1.average wait on weekends?
<br>2.average weight per week?

In [2]:
import numpy as np

dailywts = 185 - np.arange(5*7)/50

print(dailywts)
dailywts.size

[185.   184.98 184.96 184.94 184.92 184.9  184.88 184.86 184.84 184.82
 184.8  184.78 184.76 184.74 184.72 184.7  184.68 184.66 184.64 184.62
 184.6  184.58 184.56 184.54 184.52 184.5  184.48 184.46 184.44 184.42
 184.4  184.38 184.36 184.34 184.32]


35

In [3]:
dailywts.reshape(-1,7)

array([[185.  , 184.98, 184.96, 184.94, 184.92, 184.9 , 184.88],
       [184.86, 184.84, 184.82, 184.8 , 184.78, 184.76, 184.74],
       [184.72, 184.7 , 184.68, 184.66, 184.64, 184.62, 184.6 ],
       [184.58, 184.56, 184.54, 184.52, 184.5 , 184.48, 184.46],
       [184.44, 184.42, 184.4 , 184.38, 184.36, 184.34, 184.32]])

In [4]:
[np.average(dailywts.reshape(-1,7)[[i]]) for i in range(4)]

[184.94, 184.79999999999998, 184.66, 184.51999999999998]

In [9]:
# second part:
san = dailywts[6::7]
sat = dailywts[7::7]

(sum(san) + sum(sat))/(san.size+sat.size)

184.62222222222223

After binge watching the discovery channel, you ditch your job as a trial lawyer to become a gold miner
. You decide to prospect five locations underneath a 7x7 grid of land. How much gold do you uncover at each location?

In [24]:

gold = np.random.randint(low=0, high=10, size=(7,7))
gold
locs = np.random.randint(low=0, high=7, size=(5,2))
gold,locs

(array([[5, 6, 4, 8, 8, 5, 7],
        [0, 9, 0, 9, 8, 6, 9],
        [7, 3, 3, 6, 4, 7, 5],
        [1, 8, 9, 0, 1, 1, 9],
        [0, 0, 1, 7, 3, 7, 9],
        [9, 2, 7, 0, 5, 3, 6],
        [1, 2, 3, 6, 0, 0, 1]]),
 array([[4, 0],
        [2, 4],
        [6, 2],
        [1, 4],
        [4, 5]]))

In [23]:
cach = gold[locs[:,0],locs[:,1]]
potential = np.average(cach)/np.mean(gold)

print(cach,"\n")

print(f"we catch {np.sum(cach)},and we use {potential*100} of our talent")


[5 5 9 0 9] 

we catch 28,and we use 110.2008032128514 of our talent


You decide to invest in a series of billboards along interstate 10 to advertise your stylish new chicken restaurant, Chic-fil-A 🐔.

    You buy three billboards evenly spaced starting from mile marker 17 and ending on mile marker 28.
    You buy another three billboards starting on mile marker 32 and ending on mile marker 36.
    In order, from mile marker 17 to 36, your billboards display these ads: A, B, C, C, B, A.

Determine how far each B ad is from your restaurant which is located at mile marker 30.

In [51]:
#calcluate b dectence from restaurant
B = np.abs(np.vstack((np.linspace(17,28,3),np.linspace(32,36,3)))-30)
B_alternative =np.abs(np.linspace([17,32],[28,36],3,axis=1)-30)

print( B_alternative ,"\n", B)

#spread b distance from area
B[:,1]

[[13.   7.5  2. ]
 [ 2.   4.   6. ]] 
 [[13.   7.5  2. ]
 [ 2.   4.   6. ]]


array([7.5, 4. ])

You’re a relationship scientist, and you’ve developed a questionnaire that determines a person’s love score - a real-valued number between 0 and 100. Your theory is that two people with similar love scores should make a good match 👩‍❤️‍💋‍👨

Given the love scores for 10 different people, create a 2-d array where (i,j) gives the absolute difference of the love scores for person i and person j.